### ISSUE TITLE
Change 'highlight current line' color in gedit

### ISSUE THREAD

**Issue by robertpainsi** [rbrito/pkg-mediterranean-gtk-themes#35]
_OS:_ Ubuntu 14.10
_Themes:_ MediterraneanDarkest
_gtk-3-version:_ 3.12.2-0ubuntu15.2
_gtk-2-version:_ 2.24.25-0ubuntu1

_What steps will reproduce the issue?_
- Open gedit.
- Enable current line highlighting (Edit -> Preferences -> Highlight current line)
- Go to a line with a white text.

![screenshot from 2015-02-28 14 18 44](https://cloud.githubusercontent.com/assets/1794599/6426346/173ea464-bf56-11e4-8a6d-47c77bf9cc21.png)

_What do you see?_
White text in the highlighted line is hardly readable.

_What is the expected output?_
The highlighting color should just be slightly different than the background color.

**Comment by robertpainsi** [comment]
The highlighted line color is configured by the gedit theme and _not_ by the gtk theme. Closed!
More infos: http://askubuntu.com/a/575349

**Comment by rbrito** [comment]
Hi, Robert.

On May 02 2015, Robert Painsi wrote:

> The highlighted line color is configured by the gedit theme and _not_ by
> the gtk theme. Closed!
> More infos: http://askubuntu.com/a/575349

Great, but from what I understood, _we_ should provide the gedit theme,
right?  Or not?

It would be good to have things working out-of-the-box for any user,
anyway...

Thanks,

## 

Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://rb.doesntexist.org/blog : Projects : https://github.com/rbrito/
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br
