### ISSUE TITLE
The project should be renamed

### ISSUE THREAD

**Issue by rbrito** [rbrito/pkg-mediterranean-gtk-themes#41]
This project started its life as a mix of integrating some patches and, also, creating Debian packages, with most of the focus on the packaging side.

This is the reason for the `pkg-` prefix in the name of the repository, but, now, the project has shifted its focus and it is more of a development nature than of a packaging one.

Therefore, I think that it would be fit to rename this repository and kill the `pkg-` prefix.

What do you think? Comments are highly welcome.

Thanks,
Rogério Brito.

**Comment by robertpainsi** [comment]
:+1:

**Comment by rbrito** [comment]
Great, thanks.

**Comment by rbrito** [comment]
Just did that. :) Thanks.

**Comment by robertpainsi** [comment]
nice!
