### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ZatsuneSakurako** [rbrito/pkg-mediterranean-gtk-themes#44]
Could it be possible to have .deb files to make installation or update easier?

**Comment by Alanaktion** [comment]
I don't know if @rbrito plans on packing it himself, but here's the current `master` as a .deb:
[mediterranean-gtk-themes.deb](http://mirror.phpizza.com/deb/mediterranean-gtk-themes.deb)

This [script](https://gist.github.com/Alanaktion/072561071b22fb94f298) will  work to package it for you for future versions:

``` bash
#!/bin/bash
mkdir -p mediterranean-gtk-themes/usr/share/ && cd $_
git clone --depth=1 https://github.com/rbrito/mediterranean-gtk-themes.git themes
cd themes
VER=$(git rev-parse --short=12 HEAD)
rm -rf .git
rm LICENSE README.md
cd ../../..
mkdir DEBIAN
cat >DEBIAN/control <<EOL
Package: mediterranean-gtk-themes
Version: $VER
Architecture: all
Maintainer: Rogério Brito <rbrito@ime.usp.br>
Description: Maintenance fork of the Mediterranean theme for GTK2/3.

EOL
cd ..
dpkg-deb --build mediterranean-gtk-themes
```

**Comment by ZatsuneSakurako** [comment]
Thanks, I have my own personal repo, so it'll help ^^
