### ISSUE TITLE
Titlebar problem in Xubuntu 15.10

### ISSUE THREAD

**Issue by ZatsuneSakurako** [rbrito/pkg-mediterranean-gtk-themes#45]
Some applications like https://github.com/baedert/corebird have transparent title bar, and it make some part unreadable, could it be fixed?
( http://screencloud.net/v/non1 )

**Comment by Alanaktion** [comment]
This seems like an issue with GTK 3's client-side decorations. I'm seeing the same issue with Xfce on Arch Linux running File Roller and other applications that use CSDs.
